services:
  - type: web
    name: esgi-test
    runtime: node
    repo: https://github.com/Yoploo/render-test-blueprint
    region: frankfurt
    plan: free
    branch: main
    buildCommande: bundle install
    startCommande: bundle exec ruby main.rb
    envVars:
      - key: DB_CONNECTION_STRING
        fromDatabase:
          name: test
          property: connectionString

databases:
  - name: test
    region: frankfurt
    plan: free
  