services:
  - type: web
    name: esgi-test
    runtime: node
    repo: https://github.com/Yoploo/render-test-blueprint # optional
    region: frankfurt # optional (defaults to oregon)
    plan: free # optional (defaults to starter instance type)
    branch: main # optional (defaults to master)
    buildCommande: npm install
    startCommande: npm run start
    envVars:
      - key: DB_CONNECTION_STRING
        fromDatabase:
          name: test
          property: connectionString

databases:
  - name: test
    region: frankfurt
  